### ISSUE TITLE
Are there any references/docs on the insert function?

### ISSUE THREAD

**Issue by vhexs** [brianc/node-sql#284]
I can't find anything, anywhere. The tests don't help and the docs are almost empty. I just need to know the syntax. An example would be good.

**Comment by danrzeppa** [comment]
Given this table definition:
```
var user = sql.define({
  name: 'user',
  columns: ['id', 'name', 'email', 'lastLogin']
});
```
an insert of one row (with just the name and email columns) would be constructed like:
```
var fields={
  name:"joe",
  email:"joe@test.com"
}
var query=user.insert(fields)
```
`query.toQuery().text` equals:
```sql
INSERT INTO "user" ("name", "email") VALUES ($1, $2)
```
where the $1 and $2 parameters equal "joe" and "joe@test.com" respectively.

You can also insert multiple rows by passing an array to the insert function instead of an object:
```
var rows=[
  {name:"joe",email:"joe@test.com"},
  {name:"sally",email:'sally@test.com'}
]
var query=user.insert(rows)
```
this will generate
```sql
INSERT INTO "user" ("name", "email") VALUES ($1, $2), ($3, $4)
```
with the parameters being equal to 'joe', 'joe@test.com', 'sally', 'sally@test.com'

**Comment by vhexs** [comment]
Ah, thanks. I changed to a module that would let me write the queries myself, however I'll keep this in mind for next time.
